SecuritySystem/Models/ErrorViewModel.cs
namespace SecuritySystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SecuritySystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SecurityDataModel;
using SecuritySystem.Models;
using System.Diagnostics;

namespace SecuritySystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(OfficerData officerData)
        {
            return View(officerData);
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SecuritySystem/Controllers/OfficerController.cs
using Microsoft.AspNetCore.Mvc;
using SecurityDataModel;
using SecuritySystem.Models;
using System.Collections.Generic;

namespace SecuritySystem.Controllers
{
    public class OfficerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OfficerController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<OfficerData> GetOfficerData = _context.OfficerDatas.OrderByDescending(x=>x.OfficerRegistrationTime).ToList();
            return View(GetOfficerData);
        }
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OfficerData data)
        {
            if (ModelState.IsValid)
            {
                _context.OfficerDatas.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(data);
        }
        public IActionResult Edit(int Id)
        {
           if(Id == 0)
            {
                return NotFound();
            }
           var data = _context.OfficerDatas.Find(Id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(OfficerData data)
        {
            if (ModelState.IsValid)
            {
                _context.OfficerDatas.Update(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(data);
        }
        public IActionResult Details(int Id)
        {
            var data = _context.OfficerDatas.FirstOrDefault(x=>x.OfficerId == Id);
            return View(data);
        }
        public IActionResult Delete(int Id)
        {
            if (Id == 0)
            {
                return NotFound();
            }
            var data = _context.OfficerDatas.Find(Id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }
    
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public IActionResult DeletePost(int? Id)
            {
                var delete = _context.OfficerDatas.Find(Id);
                if (delete == null)
                {
                    return NotFound();
                }
                _context.OfficerDatas.Remove(delete);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }

SecuritySystem/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecurityDataModel;
using SecuritySystem.Models;
using SecuritySystem.ModelsViewData;


namespace SecuritySystem.Controllers
{
    public class SecurityController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SecurityController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            var dataModels = _context.SecurityDatas.Include(x=>x.StoresDatas)              

            return View(dataModels);
        }
        public IActionResult Create()
        {
            var data = new SecurityDataView();
            data.SecurityData = new SecurityData();
            data.StoresDatas = _context.StoresDatas.ToList();
            data.OfficerDatas = _context.OfficerDatas.ToList();
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SecurityData securityData)
        {
            if (ModelState.IsValid)
            {                               
                _context.SecurityDatas.Add(securityData);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var dataview = new SecurityDataView();
            dataview.SecurityData = new SecurityData();
            dataview.StoresDatas = _context.StoresDatas.ToList();
            dataview.OfficerDatas = _context.OfficerDatas.ToList();

            return View(dataview);
        }
        public IActionResult Details(int id)
        {
            var details = _context.SecurityDatas.FirstOrDefault(x => x.Id == id);
            return View(details);
        }
    }
}

SecuritySystem/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SecurityDataModel;
using SecuritySystem.Models;

namespace SecuritySystem.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<StoresData> ObjStores = _context.StoresDatas.OrderBy(x=>x.StoreName).ToList();
            return View(ObjStores);           
        }
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StoresData data)
        {
           
            
            if (ModelState.IsValid)
            {
                _context.StoresDatas.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");   
            }
            return View(data);
        }

        public IActionResult Edit(int Id)
        {   
            if(Id == 0 )
            {
                return NotFound();
            }
            var data = _context.StoresDatas.Find(Id);  
            if(data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(StoresData data)
        {
            if (ModelState.IsValid)
            {
                _context.StoresDatas.Update(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(data);
        }
       
        public async Task<IActionResult> Delete(int Id)
        {
            if (Id == 0)
            {
                return NotFound();
            }
            var del = await _context.StoresDatas.FirstOrDefaultAsync(m => m.StoreId == Id);          
            if(del == null)
            {
                return NotFound();
            }
            return View(del);
        }
        [HttpPost, ActionName("Delete")]  
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            var delete = _context.StoresDatas.Find(Id);
            if(delete == null)
            {
                return NotFound();
            }
            _context.StoresDatas.Remove(delete);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Details(int Id)
        {
            var details = _context.StoresDatas.FirstOrDefault(x => x.StoreId == Id);
            return View(details);   
        }
    }
}

SecuritySystem/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Page";
}
<h1>@ViewData["Title"]</h1>

<p>Security App</p>

SecuritySystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<body class="bg-image">
<div class="container border-2" >  
        <div class="text-center">
            <h1 class="display-4">Welcome</h1>
            <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        </div>  
        
</div>
</body>

SecuritySystem/Views/Officer/Create.cshtml
@model SecurityDataModel.OfficerData

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>OfficerData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OfficerName" class="control-label"></label>
                <input asp-for="OfficerName" class="form-control" />
                <span asp-validation-for="OfficerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficerGender" class="control-label"></label>
                <select asp-for="OfficerGender" class="form-control">
                    <option value="0" disabled selected>-- Select Gender --</option>
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>
                <span asp-validation-for="OfficerGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SecuritySystem/Views/Officer/Delete.cshtml
@model SecurityDataModel.OfficerData

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OfficerData</h4>
    <hr />
    <form asp-action="Delete">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerRegistrationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerRegistrationTime)
        </dd>
    </dl>
    
  
        <input type="hidden" asp-for="OfficerId" />
        <button type="submit" value="Delete" class="btn btn-outline-danger" onclick= "return confirm('Are you sure you want to Delete this Officer?')">Delete Officer</button> |
        <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
    </form>
</div>

SecuritySystem/Views/Officer/Details.cshtml
@model SecurityDataModel.OfficerData

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OfficerData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficerRegistrationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficerRegistrationTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OfficerId" class="btn btn-outline-info">Edit</a> |
    <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
</div>

SecuritySystem/Views/Officer/Edit.cshtml
@model SecurityDataModel.OfficerData

@{
    ViewData["Title"] = "Edit";
}


<h5 style="margin-top:3px">Officer details change</h5>
<hr class="text-success"/>
        <form asp-action="Edit">
             <div class="contain-center">
                <div class="border border-success p-3 mt-4">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="OfficerId" />
                    <div class="form-group mb-3">
                        <label asp-for="OfficerName" class="control-label"></label>
                        <input asp-for="OfficerName" class="form-control"/>
                        <span asp-validation-for="OfficerName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="OfficerGender" class="control-label"></label>
                        <select asp-for="OfficerGender" class="form-select">
                            <option value="0">-- Select Gender</option>
                            <option value="1">Male</option>
                            <option value="2">Female</option>
                        </select>
                        <span asp-validation-for="OfficerGender" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3"> 
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Mobile" class="control-label"></label>
                        <input asp-for="Mobile" class="form-control" />
                        <span asp-validation-for="Mobile" class="text-danger"></span>
                    </div>
         
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-info" style="width:150px">Save Changes</button>
                        &nbsp;
                        <a asp-action="Index" class="btn btn-outline-secondary" style="width:150px">Back to List</a>
                    </div>          
                </div>
            </div>
        </form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SecuritySystem/Views/Officer/Index.cshtml
@model IEnumerable<SecurityDataModel.OfficerData>

@{
    ViewData["Title"] = "Index";
}

<h4>Security Officer staff list</h4>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OfficerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficerGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficerRegistrationTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OfficerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficerGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficerRegistrationTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OfficerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OfficerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OfficerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SecuritySystem/Views/Security/Index.cshtml
@model IEnumerable<SecurityDataModel.SecurityData>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h4 class="text-primary">Suspect's List</h4>
        </div>
        <div class="col-6 text-end" >
            <a asp-controller="Security" asp-action="Create" class="btn btn-outline-success">
                <i class="bi bi-plus-square"></i> &nbsp; Add a new Suspect</a>
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.Officer_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuspectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IncidentDetails)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PoliceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PoilceBadgeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store_Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelitem=>item.GetOfficers.OfficerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuspectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IncidentDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PoliceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PoilceBadgeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GetStores.StoreId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SecuritySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SecuritySystem</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.solar.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SecuritySystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Security" asp-action="Index"><i class="bi bi-person-lines-fill"></i> Suspect List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Store" asp-action="Index"><i class="bi bi-gear"></i> Store Settings</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Officer" asp-action="Index"><i class="bi bi-people-fill"></i> Officers</a>
        </li>
    @*    <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"  role="button" aria-haspopup="true" aria-expanded="false">Stores</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" asp-controller="Store" asp-action="Index">Queenspark PO</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
      @*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SecuritySystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SecuritySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SecuritySystem/Views/Store/Index.cshtml
@model IEnumerable<SecurityDataModel.StoresData>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h4 class="text-primary">Store List</h4>
        </div>
        <div class="col-6 text-end" >
            <a asp-controller="Store" asp-action="Create" class="btn btn-outline-success">
                <i class="bi bi-plus-square"></i> &nbsp; Add a New Store</a>
        </div>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StoreName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoreAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StorePhone)
            </th>
            <th>
                <h5>Actions</h5>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StoreName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StoreAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StorePhone)
            </td>
            <td>
                <div class="btn-group">
                    <a asp-action="Edit" asp-route-id="@item.StoreId" class="btn btn-outline-info"><i class="bi bi-pencil-square"></i> Edit</a> &nbsp; | &nbsp;
                    <a asp-action="Details" asp-route-id="@item.StoreId" class="btn btn-outline-secondary"><i class="bi bi-info-square"></i> Details</a> &nbsp; | &nbsp;
                    <a asp-action="Delete" asp-route-id="@item.StoreId" class="btn btn-outline-danger"><i class="bi bi-trash"></i> Delete</a>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>